### ISSUE TITLE
Plugin not detected when using Python3.8

### ISSUE THREAD

**Issue by d0mnik** [yossizap/angrcutter#5]
The plugin is not loaded when the default python3 version is Python3.8

The following errors are generated:
```
Setting PYTHONHOME = "/tmp/.mount_cuttervR0yBO/usr"  for AppImage.
PYTHONHOME = "/tmp/.mount_cuttervR0yBO/usr"
Setting r2 prefix = "/tmp/.mount_cuttervR0yBO/usr"  for AppImage.
Setting r2 plugins dir = "/tmp/.mount_cuttervR0yBO/usr/share/radare2/plugins"
Plugins are loaded from "/root/.local/share/RadareOrg/Cutter/plugins"
/usr/bin/ld: cannot find -lpython3.6m
collect2: error: ld returned 1 exit status
Couldn't load module for plugin: "angrcutter"
Traceback (most recent call last):
  File "/tmp/.mount_cuttervR0yBO/usr/lib/python3.6/distutils/unixccompiler.py", line 196, in link
    self.spawn(linker + ld_args)
  File "/tmp/.mount_cuttervR0yBO/usr/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/tmp/.mount_cuttervR0yBO/usr/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/tmp/.mount_cuttervR0yBO/usr/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/RadareOrg/Cutter/plugins/python/angrcutter/__init__.py", line 1, in <module>
    from .plugin_interface import create_cutter_plugin
  File "/root/.local/share/RadareOrg/Cutter/plugins/python/angrcutter/plugin_interface.py", line 3, in <module>
    from .plugin import AngrWidget, printMessage, LogLevel
  File "/root/.local/share/RadareOrg/Cutter/plugins/python/angrcutter/plugin.py", line 6, in <module>
    from .debugger import cutterDebugger
  File "/root/.local/share/RadareOrg/Cutter/plugins/python/angrcutter/debugger.py", line 6, in <module>
    from angrdbg import *
  File "/usr/local/lib/python3.8/dist-packages/angrdbg/__init__.py", line 6, in <module>
    from .core import get_logger, StateShot, StateManager, get_registers
  File "/usr/local/lib/python3.8/dist-packages/angrdbg/core.py", line 6, in <module>
    from .context import load_project, get_memory_type, set_memory_type, get_debugger, SIMPROCS_FROM_CLE, ONLY_GOT_FROM_CLE, GET_ALL_DISCARD_CLE
  File "/usr/local/lib/python3.8/dist-packages/angrdbg/context.py", line 6, in <module>
    import angr
  File "/usr/local/lib/python3.8/dist-packages/angr/__init__.py", line 30, in <module>
    from .sim_procedure import SimProcedure
  File "/usr/local/lib/python3.8/dist-packages/angr/sim_procedure.py", line 5, in <module>
    from cle import SymbolType
  File "/usr/local/lib/python3.8/dist-packages/cle/__init__.py", line 18, in <module>
    from .loader import *
  File "/usr/local/lib/python3.8/dist-packages/cle/loader.py", line 14, in <module>
    import claripy
  File "/usr/local/lib/python3.8/dist-packages/claripy/__init__.py", line 21, in <module>
    from . import backends as _backends_module
  File "/usr/local/lib/python3.8/dist-packages/claripy/backends/__init__.py", line 785, in <module>
    from .backend_smtlib import BackendSMTLibBase
  File "/usr/local/lib/python3.8/dist-packages/claripy/backends/backend_smtlib.py", line 3, in <module>
    from pysmt.shortcuts import Symbol, String, StrConcat, NotEquals, \
  File "/usr/local/lib/python3.8/dist-packages/pysmt/shortcuts.py", line 38, in <module>
    import pysmt.smtlib.parser
  File "/usr/local/lib/python3.8/dist-packages/pysmt/smtlib/parser/__init__.py", line 91, in <module>
    pyxbuild_dir=build_dir)
  File "/usr/lib/python3/dist-packages/pyximport/pyximport.py", line 191, in build_module
    reload_support=pyxargs.reload_support)
  File "/usr/lib/python3/dist-packages/pyximport/pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()
  File "/tmp/.mount_cuttervR0yBO/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/tmp/.mount_cuttervR0yBO/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/tmp/.mount_cuttervR0yBO/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/lib/python3/dist-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/tmp/.mount_cuttervR0yBO/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/tmp/.mount_cuttervR0yBO/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/tmp/.mount_cuttervR0yBO/usr/lib/python3.6/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/tmp/.mount_cuttervR0yBO/usr/lib/python3.6/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/tmp/.mount_cuttervR0yBO/usr/lib/python3.6/distutils/unixccompiler.py", line 198, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1
Plugin module does not contain create_cutter_plugin() function: "cutterref"
Loaded 0 plugin(s).

```

**Comment by gabriele-costa** [comment]
I also can't load the plugin, but no error is returned (see screenshots). I am using Python 3.6
![Schermata del 2020-11-17 18-07-46](https://user-images.githubusercontent.com/10499254/99422656-0d037000-2900-11eb-811d-81067f05c07b.png)
![Schermata del 2020-11-17 18-10-21](https://user-images.githubusercontent.com/10499254/99422990-62d81800-2900-11eb-99ee-0fb733445750.png)
