### ISSUE TITLE
No module named angrdbg

### ISSUE THREAD

**Issue by Shivanshu10** [yossizap/angrcutter#6]
on executing cutter:
```
Setting PYTHONHOME = "/tmp/.mount_cutterFJUELh/usr"  for AppImage.
PYTHONHOME = "/tmp/.mount_cutterFJUELh/usr"
Setting r2 prefix = "/tmp/.mount_cutterFJUELh/usr"  for AppImage.
Setting r2 plugins dir = "/tmp/.mount_cutterFJUELh/usr/share/radare2/plugins"
Plugins are loaded from "/home/shivanshu/.local/share/RadareOrg/Cutter/plugins"
Couldn't load module for plugin: "angrcutter"
Traceback (most recent call last):
  File "/home/shivanshu/.local/share/RadareOrg/Cutter/plugins/python/angrcutter/__init__.py", line 1, in <module>
    from .plugin_interface import create_cutter_plugin
  File "/home/shivanshu/.local/share/RadareOrg/Cutter/plugins/python/angrcutter/plugin_interface.py", line 3, in <module>
    from .plugin import AngrWidget, printMessage, LogLevel
  File "/home/shivanshu/.local/share/RadareOrg/Cutter/plugins/python/angrcutter/plugin.py", line 6, in <module>
    from .debugger import cutterDebugger
  File "/home/shivanshu/.local/share/RadareOrg/Cutter/plugins/python/angrcutter/debugger.py", line 6, in <module>
    from angrdbg import *
ModuleNotFoundError: No module named 'angrdbg'
Plugin module does not contain create_cutter_plugin() function: "cutterref"
Loaded 1 plugin(s).
Plugins are loaded from "/usr/share/xfce4/RadareOrg/Cutter/plugins"
Plugins are loaded from "/usr/local/share/RadareOrg/Cutter/plugins"
Plugins are loaded from "/usr/share/RadareOrg/Cutter/plugins"
Plugins are loaded from "/tmp/.mount_cutterFJUELh/usr/share/RadareOrg/Cutter/plugins"
Loaded 1 plugin(s).
```
I am getting ModuleNotFound even if i have installed angrdbg
```
python3 -m pip install angrdbg
```
output is:
```
Requirement already satisfied: angrdbg in ./Programs/anaconda3/lib/python3.8/site-packages (1.0.16)
Requirement already satisfied: angr in ./Programs/anaconda3/lib/python3.8/site-packages (from angrdbg) (9.0.5610)
Requirement already satisfied: ipython in ./Programs/anaconda3/lib/python3.8/site-packages (from angrdbg) (7.19.0)
Requirement already satisfied: rpyc in ./Programs/anaconda3/lib/python3.8/site-packages (from angrdbg) (5.0.1)
Requirement already satisfied: ailment==9.0.5610 in ./Programs/anaconda3/lib/python3.8/site-packages (from angr->angrdbg) (9.0.5610)
Requirement already satisfied: progressbar2 in ./Programs/anaconda3/lib/python3.8/site-packages (from angr->angrdbg) (3.53.1)
Requirement already satisfied: protobuf>=3.12.0 in ./Programs/anaconda3/lib/python3.8/site-packages (from angr->angrdbg) (3.14.0)
Requirement already satisfied: cle==9.0.5610 in ./Programs/anaconda3/lib/python3.8/site-packages (from angr->angrdbg) (9.0.5610)
Requirement already satisfied: cachetools in ./Programs/anaconda3/lib/python3.8/site-packages (from angr->angrdbg) (4.2.0)
Requirement already satisfied: claripy==9.0.5610 in ./Programs/anaconda3/lib/python3.8/site-packages (from angr->angrdbg) (9.0.5610)
Requirement already satisfied: dpkt in ./Programs/anaconda3/lib/python3.8/site-packages (from angr->angrdbg) (1.9.4)
Requirement already satisfied: cffi>=1.14.0 in ./Programs/anaconda3/lib/python3.8/site-packages (from angr->angrdbg) (1.14.4)
Requirement already satisfied: pyvex==9.0.5610 in ./Programs/anaconda3/lib/python3.8/site-packages (from angr->angrdbg) (9.0.5610)
Requirement already satisfied: mulpyplexer in ./Programs/anaconda3/lib/python3.8/site-packages (from angr->angrdbg) (0.9)
Requirement already satisfied: psutil in ./Programs/anaconda3/lib/python3.8/site-packages (from angr->angrdbg) (5.8.0)
Requirement already satisfied: GitPython in ./Programs/anaconda3/lib/python3.8/site-packages (from angr->angrdbg) (3.1.12)
Requirement already satisfied: sortedcontainers in ./Programs/anaconda3/lib/python3.8/site-packages (from angr->angrdbg) (2.3.0)
Requirement already satisfied: archinfo==9.0.5610 in ./Programs/anaconda3/lib/python3.8/site-packages (from angr->angrdbg) (9.0.5610)
Requirement already satisfied: capstone>=3.0.5rc2 in ./Programs/anaconda3/lib/python3.8/site-packages (from angr->angrdbg) (4.0.2)
Requirement already satisfied: networkx>=2.0 in ./Programs/anaconda3/lib/python3.8/site-packages (from angr->angrdbg) (2.5)
Requirement already satisfied: itanium-demangler in ./Programs/anaconda3/lib/python3.8/site-packages (from angr->angrdbg) (1.0)
Requirement already satisfied: unicorn==1.0.2rc4 in ./Programs/anaconda3/lib/python3.8/site-packages (from angr->angrdbg) (1.0.2rc4)
Requirement already satisfied: CppHeaderParser in ./Programs/anaconda3/lib/python3.8/site-packages (from angr->angrdbg) (2.7.4)
Requirement already satisfied: pycparser>=2.18 in ./Programs/anaconda3/lib/python3.8/site-packages (from angr->angrdbg) (2.20)
Requirement already satisfied: z3-solver>=4.8.5.0 in ./Programs/anaconda3/lib/python3.8/site-packages (from claripy==9.0.5610->angr->angrdbg) (4.8.10.0)
Requirement already satisfied: future in ./Programs/anaconda3/lib/python3.8/site-packages (from claripy==9.0.5610->angr->angrdbg) (0.18.2)
Requirement already satisfied: pysmt in ./Programs/anaconda3/lib/python3.8/site-packages (from claripy==9.0.5610->angr->angrdbg) (0.9.0)
Requirement already satisfied: decorator in ./Programs/anaconda3/lib/python3.8/site-packages (from claripy==9.0.5610->angr->angrdbg) (4.4.2)
Requirement already satisfied: pefile in ./Programs/anaconda3/lib/python3.8/site-packages (from cle==9.0.5610->angr->angrdbg) (2019.4.18)
Requirement already satisfied: pyelftools>=0.25 in ./Programs/anaconda3/lib/python3.8/site-packages (from cle==9.0.5610->angr->angrdbg) (0.27)
Requirement already satisfied: bitstring in ./Programs/anaconda3/lib/python3.8/site-packages (from pyvex==9.0.5610->angr->angrdbg) (3.1.7)
Requirement already satisfied: six>=1.9 in ./Programs/anaconda3/lib/python3.8/site-packages (from protobuf>=3.12.0->angr->angrdbg) (1.15.0)
Requirement already satisfied: ply in ./Programs/anaconda3/lib/python3.8/site-packages (from CppHeaderParser->angr->angrdbg) (3.11)
Requirement already satisfied: gitdb<5,>=4.0.1 in ./Programs/anaconda3/lib/python3.8/site-packages (from GitPython->angr->angrdbg) (4.0.5)
Requirement already satisfied: smmap<4,>=3.0.1 in ./Programs/anaconda3/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->GitPython->angr->angrdbg) (3.0.5)
Requirement already satisfied: pygments in ./Programs/anaconda3/lib/python3.8/site-packages (from ipython->angrdbg) (2.7.3)
Requirement already satisfied: setuptools>=18.5 in ./Programs/anaconda3/lib/python3.8/site-packages (from ipython->angrdbg) (51.0.0)
Requirement already satisfied: pexpect>4.3 in ./Programs/anaconda3/lib/python3.8/site-packages (from ipython->angrdbg) (4.8.0)
Requirement already satisfied: pickleshare in ./Programs/anaconda3/lib/python3.8/site-packages (from ipython->angrdbg) (0.7.5)
Requirement already satisfied: backcall in ./Programs/anaconda3/lib/python3.8/site-packages (from ipython->angrdbg) (0.2.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in ./Programs/anaconda3/lib/python3.8/site-packages (from ipython->angrdbg) (3.0.8)
Requirement already satisfied: traitlets>=4.2 in ./Programs/anaconda3/lib/python3.8/site-packages (from ipython->angrdbg) (5.0.5)
Requirement already satisfied: jedi>=0.10 in ./Programs/anaconda3/lib/python3.8/site-packages (from ipython->angrdbg) (0.17.2)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in ./Programs/anaconda3/lib/python3.8/site-packages (from jedi>=0.10->ipython->angrdbg) (0.7.0)
Requirement already satisfied: ptyprocess>=0.5 in ./Programs/anaconda3/lib/python3.8/site-packages (from pexpect>4.3->ipython->angrdbg) (0.6.0)
Requirement already satisfied: wcwidth in ./Programs/anaconda3/lib/python3.8/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->angrdbg) (0.2.5)
Requirement already satisfied: ipython-genutils in ./Programs/anaconda3/lib/python3.8/site-packages (from traitlets>=4.2->ipython->angrdbg) (0.2.0)
Requirement already satisfied: python-utils>=2.3.0 in ./Programs/anaconda3/lib/python3.8/site-packages (from progressbar2->angr->angrdbg) (2.5.5)
Requirement already satisfied: plumbum in ./Programs/anaconda3/lib/python3.8/site-packages (from rpyc->angrdbg) (1.6.9)
```
but on importing angrdbg from python interpreter:
```
(base) shivanshu@kali:~$ python3
Python 3.8.3 (default, Jul  2 2020, 16:21:59) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import angrdbg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shivanshu/Programs/anaconda3/lib/python3.8/site-packages/angrdbg/__init__.py", line 6, in <module>
    from .core import get_logger, StateShot, StateManager, get_registers
  File "/home/shivanshu/Programs/anaconda3/lib/python3.8/site-packages/angrdbg/core.py", line 14, in <module>
    from .memory_8 import SimSymbolicDbgMemory
  File "/home/shivanshu/Programs/anaconda3/lib/python3.8/site-packages/angrdbg/memory_8.py", line 17, in <module>
    from angr.storage.memory import SimMemory, DUMMY_SYMBOLIC_READ_VALUE
ModuleNotFoundError: No module named 'angr.storage.memory'
>>> 
```

**Comment by jacobjwalters** [comment]
I think this is a problem with angrdbg. It seems the latest version of angr has changed the API and the maintainer of angrdbg doesn't seem interested in updating it, unfortunately.

**Comment by vyrus001** [comment]
> I think this is a problem with angrdbg. It seems the latest version of angr has changed the API and the maintainer of angrdbg doesn't seem interested in updating it, unfortunately.

literally Just tried to install on OSX and hit the exact problem. Sad that the dev may have walked away but this is critical enough to one of my work flows that I think I will look into fixing it

**Comment by ferhaterata** [comment]
Hi @vyrus001, have you figured out a way to fix this?

**Comment by FalcoGer** [comment]
The issue is with angrdbg not working with angr version 9.

If you install angrdbg and angr with
```
pip3 install angrdbg 'angr<=9.0'
```

cutter loads the plugin (first time loading takes a while), but crashes shortly after loading. I'm using the stable branch.
